config/routes.rb
Tateopedia::Application.routes.draw do

  get "wikis/private_index"
  get "wikis/my_index"
  get "wikis/collaborations_index"

  devise_for :users 

  resources :wikis do
    resources :collaborators
  end

  resources :users, only: [:update, :show, :index]

  resources :charges, only: [:new, :create, :destroy]

  authenticated :user do
    root to: 'wikis#index', as: 'authenticated_root'
  end
  
  get 'about' => 'welcome#about'
  
  root to: 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
 belongs_to :user
 belongs_to :wiki
 default_scope { order('updated_at DESC') }
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_collaborator, only: [:show, :edit, :update, :destroy]
  before_action :set_wiki, only: [:new, :create, :index, :destroy]

  def index
    @collaborators = @wiki.collaborators

  end

  def show
    @collaborators = @wiki.collaborators
  end

  def new
    @new_collaborator = Collaborator.new
    collaborator_ids = @wiki.collaborators.pluck(:user_id)
    @collaborator_users = User.where.not(id: collaborator_ids).not(current_user.id)
  end


  def edit
    @collaborators = @wiki.collaborators
  end

  def create
    @collaborator = @wiki.collaborators.build(collaborator_params)

    respond_to do |format|
       if @collaborator.save
         @user = @collaborator.user
         @user.update(member: true)
         @wiki.update(collaboration: true)
        format.html { redirect_to wiki_path(@wiki), notice: 'Collaborator was successfully added.' }
        format.json { render :edit, status: :created, location: @collaborator }
       else
        format.html { render :new }
        format.json { render json: @collaborator.errors, status: :unprocessable_entity }
       end
    end
  end


  def update
      if @collaborator.update(collaborator_params)
        flash[:notice] = 'Collaborator was successfully updated.' 
        redirect_to @collaborator
      else
        flash[:error] = "No can do. Try Again!"
        render :edit
      end
  end


  def destroy
    @collaborator.destroy
    respond_to do |format|
      format.html { redirect_to edit_wiki_path(@wiki), notice: 'Collaborator was successfully removed.' }
      format.json { head :no_content }
     
    end
  end

  private
    
  def set_collaborator
    @collaborator = Collaborator.find(params[:id])
  end

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

  def collaborator_params
    params.require(:collaborator).permit(:user_id, :wiki_id)
  end
end

app/views/collaborators/_collaborator.html.erb
 <tr>
  <td><b><i><%= collaborator.user.email %></i></b></td>
  <td><%= time_ago_in_words(collaborator.created_at) %> ago</td> 

   <td><% if @wiki.user == current_user %>
    <%= link_to 'Remove', [collaborator.wiki, collaborator], method: :delete %>
    <% end %></td>
  
</tr>

app/views/collaborators/_form.html.erb
<%= form_for([@wiki, @new_collaborator]) do |f| %>
<div class='new_header'> Add a New Collaborator! </div>
  <div class="field">
    <%= f.select 'user_id', options_for_select(@collaborator_users.collect{ |u| [u.email, u.id] }) %>
  </div>
</br>
  <div class="actions">
    <%= f.submit "Add Collaborator" %>
  </div>
<% end %>

app/views/collaborators/index.html.erb
<h1><%= @wiki.title %> collaborators</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date Added</th>
    </tr>
  </thead>

  <tbody>
    <% @collaborators.each do |collaborator| %>
      <tr>
        <td><%= collaborator.user.email %></td>
        <td><%= time_ago_in_words(collaborator.created_at) %> ago</td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @wiki.user == current_user %>
<%= link_to 'New Collaborator', new_wiki_collaborator_path %> |
<% end %>
<%= link_to 'Back', wikis_path %>

app/views/collaborators/new.html.erb
<h1>New collaborator</h1>

<%= render 'form' %>

<%= link_to 'Back', wikis_path %>

app/views/collaborators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @collaborator.user %>
</p>

<p>
  <strong>Wiki:</strong>
  <%= @collaborator.wiki %>
</p>

<%= link_to 'Edit', edit_collaborator_path(@collaborator) %> |
<%= link_to 'Back', collaborators_path %>