config/routes.rb
Tateopedia::Application.routes.draw do

  get "wikis/private_index"
  get "wikis/my_index"
  get "wikis/collaborations_index"

  devise_for :users 

  resources :wikis do
    resources :collaborators
  end

  resources :users, only: [:update, :show, :index]

  resources :charges, only: [:new, :create, :destroy]

  authenticated :user do
    root to: 'wikis#index', as: 'authenticated_root'
  end
  
  get 'about' => 'welcome#about'
  
  root to: 'welcome#index'
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base

  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :public, -> { where(:private => false) }
  scope :private, -> { where(:private => true) }
  default_scope { order('created_at DESC') }


  # indentation
  
    def has_collaborators?
      self.collaboration == true
    end

    def can_be_collaboration?
     user.upgraded? && private == true
    end
   

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_user
  
  def index
    @wikis = Wiki.public.paginate(page: params[:page], per_page: 10)
  end

  def private_index
    @wikis = Wiki.private
    
    if current_user.upgraded?
      render wikis_private_index_path
    else 
      flash[:error] = "You aren't a baller. But you can upgrade here!"
      redirect_to edit_user_registration_path
    end
  end

  def my_index
    @wikis = current_user.wikis.all
    @colspan = @user.upgraded? ? 4 : 2
  end
  
  def collaborations_index
    @collaborations = current_user.wiki_collaborations
    @wikis = current_user.wikis.where(collaboration: true)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
     if user_signed_in?
      render :new
    else 
      flash[:error] = "You need to be signed up to do that!"
      redirect_to new_user_registration_path
    end
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)
    @wiki.updater = current_user.email

    respond_to do |format|
    if @wiki.save
      format.html { redirect_to @wiki, notice: "Wiki, wiki... New Wiki ya'll" }
      format.json { render :show, status: :created, location: @wiki }
    else
      format.html { render :new }
      format.json { render json: @wiki.errors, status: :unprocessable_entity }
    
    end
    end
  end


  def edit
    @wiki = Wiki.find(params[:id])
    @wiki_updater = current_user.email
    @collaborators = @wiki.collaborators
    @new_collaborator = Collaborator.new
    collaborator_ids = @wiki.collaborators.pluck(:user_id) << current_user.id
    @collaborator_users = User.where.not(id: collaborator_ids)
  end

  def update
    @wiki = Wiki.find(params[:id])

    respond_to do |format|
      if @wiki.update_attributes(params.require(:wiki).permit(:title, :body, :private, :collaboration, :updater))
        @wiki.update(updater: current_user.email)
        remove_collaborators
        format.html { redirect_to @wiki, notice: "Your Wiki is Funkier!" }
        format.json { render :show, status: :ok, location: @wiki }
      
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
     @wiki = Wiki.find(params[:id])
 
     @wiki.destroy
      respond_to do |format|
      format.html { redirect_to wikis_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }

     end
  end


  private

  def remove_collaborators
    if params[:wiki][:private] == '0'
      @wiki.collaborators.destroy_all
    end
  end

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :collaboration, :user_id, :updater)
  end

  def set_user
    @user = current_user
  end

end

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
  </div>
  <%= f.label :body %>
  <%= f.text_area :body, rows: 8, class: 'form-control' %>
  <% if @user.upgraded? && @wiki.user == current_user %>
  <div class="field">
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>
  <% end %>
</br>
  <div class="actions">
    <%= f.submit "Update Wiki", class: 'btn btn-success' %>
  <%= f.submit "Delete Wiki", class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> </div>

<% end %>

app/views/wikis/collaborations_index.html.erb
<h2>Shared Wikis</h2>

<h3>My Created Wikis</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date Created</th>
      <th>Last Updated</th>
      <th>Updated By</th> 
      <th colspan="<%= @colspan %>"></th>
      <th colspan="<%= @colspan %>"></th>
      <th colspan="<%= @colspan %>"></th>
    </tr>
  </thead>
<tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.title, wiki %></td>
        <td><%= time_ago_in_words(wiki.created_at) %> ago</td>
        <td><%= time_ago_in_words(wiki.updated_at) %> ago</td>
        <td><%= wiki.updater %></td> 
        <td><%= link_to 'View Collaborators', wiki_collaborators_path(wiki) %></td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


  <h3> Wikis Shared with Me</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created By</th>
      <th>Date Created</th>
      <th>Last Updated</th>
      <th>Updated By</th> 
      <th colspan=""></th>
    </tr>
  </thead>

  <tbody>
    <% @collaborations.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.title, wiki %></td>
        <td><%= wiki.user.email %></td>
        <td><%= time_ago_in_words(wiki.created_at) %> ago</td>
        <td><%= time_ago_in_words(wiki.updated_at) %> ago</td>
        <td><%= wiki.updater %></td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-warning' %>

app/views/wikis/edit.html.erb
<h1>Editing wiki</h1>

<%= render 'form' %>
</br>
<% if @wiki.can_be_collaboration? && @wiki.user == current_user %>
  <%= render "collaborators/form" %>
<% end %>
</br>

<% if @wiki.has_collaborators? %>
  <h4><u> Current Wiki Collaborators </u></h4>
  <table><thead>
    <tr>
      <th>User</th>
      <th> Day Added </th>
      <th colspan="<%= @colspan %>"></th>
    </tr>
  </thead>
   <tbody>
      <%= render @collaborators %>
   </tbody>
  </table>
<% end %>

<% if !@wiki.private %>
<h4><u> If you want to make this Wiki a collaboration, it needs to be privatized! </u></h4>
<% end %>

</br>

<%= link_to 'Back to Wiki', wiki_path(@wiki) %> |
<% if @wiki.user == current_user %>
  <%= link_to 'Back to My Wikis', wikis_my_index_path %>
<% else %>
  <%= link_to 'Back to Wikis', wikis_path %>
<% end %>
     
   
 

app/views/wikis/index.html.erb
<h1>All wikis</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date Created</th>
      <th>Wiki Creator</th>
      <th>Last Updated</th>
      <th>Updated By</th> 
    </tr>
  </thead>

  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.title, wiki %></td>
        <td><%= time_ago_in_words(wiki.created_at) %> ago</td>
        <td><%= wiki.user.email %></td>
        <td><%= time_ago_in_words(wiki.updated_at) %> ago</td>
        <td><%= wiki.updater %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @wikis %>
</br>
<%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-warning' %>

app/views/wikis/my_index.html.erb
<h1>My wikis</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date Created</th>
      <th>Last Updated</th>
      <th>Wiki Type</th>
      <th colspan="<%= @colspan %>"></th>
    </tr>
  </thead>

  <tbody>
 <% @wikis.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.title, wiki %></td>
        <td><%= time_ago_in_words(wiki.created_at) %> ago</td>
        <td><%= time_ago_in_words(wiki.updated_at) %> ago</td>
        <% if wiki.private? %>
        <td><div class='signature'>Private</div></td>
        <% else %>
        <td><div class='signature'>Public</div></td>
        <% end %>
         <% if wiki.can_be_collaboration? %>
        <td><%= link_to 'View Collaborators', wiki_collaborators_path(wiki) %></td>
        <td><%= link_to 'Add Collaborator', edit_wiki_path(wiki) %></td>
        <% end %>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-warning' %>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Wikis</p>
     <ul>
       <li>Make it weird!</li>
       <li>Express love.</li>
       <li>No one likes long wind. Make it short.</li>
     </ul>
   </div>

   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
        <% if current_user.upgraded? %>
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
            <% end %>
        <% end %>
      <% end %>
   </div>
 </div>

app/views/wikis/private_index.html.erb
<h1>Private wikis</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date Created</th>
      <th>Last Updated</th>
      <th colspan="<%= @colspan %>"></th>
      <th colspan="<%= @colspan %>"></th>
    </tr>
  </thead>

  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.title, wiki %></td>
        <td><%= time_ago_in_words(wiki.created_at) %> ago</td>
        <td><%= time_ago_in_words(wiki.updated_at) %> ago</td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         
      </tr>
   <% end %>
  </tbody>
</table>


<%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-warning' %>

app/views/wikis/show.html.erb
<h2> Working Wiki </h2>
<div class='wiki_mark'>
  <strong>
  <% if !@wiki.private %>
    Public Wiki
  <% else %>
    Private Wiki
  <% end %>
  </strong>
</div>
  
</br>
<p>
  <strong>Name:</strong>
  <%= markdown(@wiki.title) %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown(@wiki.body) %>
</p>
<p><div class='signature'> Created by: <%= @wiki.user.email %> <%= time_ago_in_words(@wiki.created_at) %> ago.</p></div>
<p><div class='signature'> Last Updated by: <%= @wiki.updater %> <%= time_ago_in_words(@wiki.updated_at) %> ago.</p></div>
<% if @wiki.has_collaborators? %>
  <h4><u> Current Wiki Collaborators </u></h4>
  <table><thead>
    <tr>
      <th>User</th>
      <th> Day Added </th>
      <th colspan="<%= @colspan %>"></th>
    </tr>
  </thead>
   <tbody>
      <%= render @wiki.collaborators %>
   </tbody>
  </table>
<% end %>
<% if user_signed_in? %>
  </br>
  <%= link_to 'Edit Wiki', edit_wiki_path(@wiki) %> |
<% end %>
<%= link_to 'Back', :back %> 