config/routes.rb
Tateopedia::Application.routes.draw do

  get "wikis/private_index"
  get "wikis/my_index"
  get "wikis/collaborations_index"

  devise_for :users 

  resources :wikis do
    resources :collaborators
  end

  resources :users, only: [:update, :show, :index]

  resources :charges, only: [:new, :create, :destroy]

  authenticated :user do
    root to: 'wikis#index', as: 'authenticated_root'
  end
  
  get 'about' => 'welcome#about'
  
  root to: 'welcome#index'
end

app/views/layouts/_navigation.html.erb
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  
    <ul class="nav nav-tabs">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Public Wikis', wikis_path %></li>
  <li><%= link_to 'Private Wikis', wikis_private_index_path %></li>
  <li><%= link_to 'My Wikis', wikis_my_index_path %></li>
  <% if current_user.collaboration_access? %>
  <li><%= link_to 'Collaborations', wikis_collaborations_index_path %> </li>
  <% end %>
  <li><%= link_to "#{current_user.name}'s Account", edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Home', root_path, class: 'navbar-brand' %></li>
  <li><%= link_to 'Wikis', wikis_path, class: 'navbar-brand' %></li>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tateopedia</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <%= render 'shared/flash' %>
    <%= yield %>
    </div>

  </body>
</html>